HappyHotels/HappyHotels/Controllers/HomeController.cs
using HappyHotels.Models;
using HappyHotels.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HappyHotels.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult EmailView()
        {
            if (User.IsInRole("ADMIN"))
            {
                var model = new SendEmailModel();
                ViewBag.AllEmailAddresses = GetEmails();
                return View(model);
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Unauthorized);
            }
        }

        private MultiSelectList GetEmails()
        {
            using (var context = new ApplicationDbContext())
            {
                var customerRole = context.Roles.FirstOrDefault(r => r.Name == "CUSTOMER");
                var customers = context.Users.Where(u => u.Roles.Any(r => r.RoleId == customerRole.Id)).ToList(); // get all users who are customers
                var data = context.Users.Where(u => u.Roles.Any(r => r.RoleId == customerRole.Id)).Select(c => new
                {
                    Name = c.Email,
                    Value = c.Email
                }).ToList();
                return new MultiSelectList(data, "Name", "Value");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult EmailView(SendEmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var toEmail = model.SelectedEmailAddresses.ToList();
                    String subject = model.Subject;
                    String contents = model.Contents;

                    EmailSender es = new EmailSender();
                    es.Send(toEmail, subject, contents, model.Upload);

                    ViewBag.Result = "Email has been sent.";

                    ModelState.Clear();
                    model.Contents = "";
                    model.Subject = "";
                    ViewBag.AllEmailAddresses = GetEmails();
                    return View(model);
                }
                catch
                {
                    ViewBag.AllEmailAddresses = GetEmails();
                    return View();
                }
            }
            ViewBag.AllEmailAddresses = GetEmails();
            return View();
        }
    }
}

HappyHotels/HappyHotels/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HappyHotels.Models;

namespace HappyHotels.Controllers
{
    public class HotelsController : Controller
    {
        private HappyHotelsEntities db = new HappyHotelsEntities();


        // GET: Hotels
        public ActionResult Index(String destination)
        {
            if (destination != null && destination.Trim() != "") // if searched through keyword
            {
                return View(db.Hotels.Where(h => h.address.Contains(destination) || h.city.Contains(destination)).ToList());
            }
            else
            {
                return View(db.Hotels.ToList());
            }
        }

        // GET: Hotels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        [Authorize]
        // GET: Hotels/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "hotel_id,name,description,address,city,state,country,postcode,check_in_time,check_out_time,lattitude,longitude,rating")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Hotels.Add(hotel);
                db.SaveChanges();

                db.HotelRooms.AddRange(new List<HotelRoom>() { new HotelRoom() { hotel_id=hotel.hotel_id,room_id=1,approx_price=100},
                    new HotelRoom() { hotel_id = hotel.hotel_id, room_id = 2, approx_price = 200 },
                new HotelRoom() { hotel_id=hotel.hotel_id,room_id=3,approx_price=300}});
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(hotel);
        }

        [Authorize]
        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        [Authorize]
        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "hotel_id,name,description,address,city,state,country,postcode,check_in_time,check_out_time,lattitude,longitude,rating")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }
        [Authorize]
        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        [Authorize]
        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.Hotels.Find(id);
            // delete all foreign keys first
            db.HotelAmenities.RemoveRange(hotel.HotelAmenities);
            foreach (var room in hotel.HotelRooms)
            {
                db.Bookings.RemoveRange(room.Bookings);
            }
            db.HotelRooms.RemoveRange(hotel.HotelRooms);
            db.HotelRatings.RemoveRange(hotel.HotelRatings);
            db.HotelPhotoes.RemoveRange(hotel.HotelPhotoes);
            db.HotelLandmarks.RemoveRange(hotel.HotelLandmarks);
            db.HotelContacts.RemoveRange(hotel.HotelContacts);
            db.Hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult Dashboard(int? hotelID)
        {
            List<int> ratingCount = new List<int>();
            List<decimal> ratings = new List<decimal>();
            if (hotelID != null && hotelID != 0) // if for a particular hotel
            {
                // fetch all distinct ratings for the hotel
                ratings = db.HotelRatings.Where(h => h.hotel_id == hotelID).Select(r => r.rating).Distinct().OrderBy(r => r).ToList();

                // count number of ratings per each distinct rating
                foreach (var rating in ratings)
                {
                    ratingCount.Add(db.HotelRatings.Where(h => h.hotel_id == hotelID).Count(r => r.rating == rating));
                }
            }
            else
            {
                // fetch all distinct ratings for the hotel
                ratings = db.HotelRatings.Select(r => r.rating).Distinct().OrderBy(r => r).ToList();

                // count number of ratings per each distinct rating
                foreach (var rating in ratings)
                {
                    ratingCount.Add(db.HotelRatings.Count(r => r.rating == rating));
                }
            }
            ViewBag.ratings = ratings;
            ViewBag.ratingCount = ratingCount;
            return View();
        }
    }
}

HappyHotels/HappyHotels/Views/Home/EmailView.cshtml
@model HappyHotels.Models.SendEmailModel

@{
    ViewBag.Title = "EmailView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("EmailView", "Home", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()


    if (@ViewBag.Result != null)
    {
        <div class="alert alert-info">@ViewBag.Result</div>
    }

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AllEmailAddresses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.SelectedEmailAddresses,(MultiSelectList) ViewBag.AllEmailAddresses)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Upload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    tinymce.init({
        selector: '#Contents'
    });
    </script>
}

HappyHotels/HappyHotels/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<script src="~/Scripts/jquery-3.3.1.js"></script>
<style type="text/css">
    .carousel .item {
        height: 300px;
    }

    .item img {
        position: absolute;
        top: 0;
        left: 0;
        min-height: 300px;
    }
</style>
<!-- Page Content -->
<div class="container">
    <div id="myCarousel" class="carousel slide img-fluid" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/Photos/pexels-photo-164595.jpeg" alt="abc" style="width:100%">
            </div>

            <div class="item">
                <img src="~/Photos/pexels-photo-189296.jpeg" alt="33" style="width:100%">
            </div>

            <div class="item">
                <img src="~/Photos/pexels-photo-258154.jpeg" alt="Nyork" style="width:100%">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-lg-12">
            <div class="well">
                <div class="row">

                    <h1 class="text-center">
                        Find your ideal hotel
                    </h1>
                </div>
                <br />
                <div class="row">

                    <!-- Form code begins -->
                    <form method="post">

                        <div class="col-md-offset-4 col-md-3">
                            <div>
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <div class="form-group">
                                                <label for="exampleForm2">Going to</label>
                                                <input type="text" id="destinationName" tabindex="1" title="Enter your destination city" placeholder="Destination" onchange="" class="form-control">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <br />
                                            <div class="form-group">
                                                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Hotels")?destination=' + $('#destinationName').val()">
                                                    Search
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h3 class="my-4 text-center">Why Choose Us?</h3>
        <br />
        <br />
        <div class="row">

            <div class="col-md-4 col-sm-6 mb-4">
                <div class="card">

                    <!-- Card content -->
                    <div class="card-body text-center">
                        <!-- Title -->
                        <h4 class="card-title"><a>Flexible Booking</a></h4>
                        <!-- Text -->
                        <p class="card-text">Adjust your booking with a click of a button. Easily available online</p>
                    </div>

                </div>
            </div>

            <div class="col-md-4 col-sm-6 mb-4">
                <div class="card">
                    <div class="card-body text-center">

                        <!-- Title -->
                        <h4 class="card-title"><a>Discover</a></h4>
                        <!-- Text -->
                        <p class="card-text">Discover, book and manage your trip from anywhere anytime.</p>
                    </div>

                </div>
            </div>

            <div class="col-md-4 col-sm-6 mb-4">
                <div class="card">
                    <div class="card-body text-center">

                        <!-- Title -->
                        <h4 class="card-title"><a>Trusted Services</a></h4>
                        <!-- Text -->
                        <p class="card-text">Our Trusted Services guarantee your booking, so that you never have to worry!</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <br />
        <br />
        <h3 class="my-4 text-center">Popular Cities</h3>
        <br />
        <br />
        <div class="row">
            <ul class="thumbnails list-unstyled">
                <li class="col-md-4">
                    <a href="@Url.Action("Index", "Hotels")?destination=Melbourne">
                        <div class="thumbnail" style="padding: 0">
                            <div style="padding:4px">
                                <img alt="300x200" style="width: 100%" src="~/Photos/melbournefree.jpg">
                            </div>
                            <div class="caption">
                                <h2>Melbourne</h2>
                                <p><i class="icon icon-map-marker"></i>Victoria, Australia</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-md-4">
                    <a href="@Url.Action("Index", "Hotels")?destination=Sydney">
                        <div class="thumbnail" style="padding: 0">
                            <div style="padding:4px">
                                <img alt="300x200" style="width: 100%" src="~/Photos/sydneyfree1.jpg">
                            </div>
                            <div class="caption">
                                <h2>Sydney</h2>
                                <p><i class="icon icon-map-marker"></i>NSW, Australia</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="col-md-4">
                    <a href="@Url.Action("Index", "Hotels")?destination=Brisbane">
                        <div class="thumbnail" style="padding: 0">
                            <div style="padding:4px">
                                <img alt="300x200" style="width: 100%" src="~/Photos/brisfree.jpg">
                            </div>
                            <div class="caption">
                                <h2>Brisbane</h2>
                                <p><i class="icon icon-map-marker"></i>Queensland, Australia</p>
                            </div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>